baseurl: https://demo.stack.jimmycai.com
languageCode: en-us
paginate: 5
title: Hi! I'm Fonti
DefaultContentLanguage: en
hasCJKLanguage: no
disqusShortname: hugo-theme-stack

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/fontikar
    - name: Twitter
      url: https://twitter.com/fonti_kar