baseurl: https://itsmontywithaf.netlify.app/
languageCode: en-us
paginate: 5
title: oh hellooo
DefaultContentLanguage: en
hasCJKLanguage: no
disqusShortname: hugo-theme-stack

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  post: /:year/:month/:day/:slug/


